apiVersion: v1 # deployment api版本
kind: Service # 资源类型为service
metadata: # service 相关元数据，用于描述service的配置
  name: nginx-svc # service名称
  labels: # 定义service的标签
    app: nginx # 标签vaule的形式，名为app，值为nginx
spec: # 期望service按照以下描述开始创建
  selector:
    app: nginx-deploy
  ports:
  - port: 80
    targetPort: 80
    name: web
  type: NodePort
