apiVersion: v1
kind: PersistentVolume # 描述资源对象为pv
metadata:
  name: pv0001 # pv 名字
spec:
  capacity: # 容量配置
    storage: 5Gi # pv 的容量
  volumeMode: Filesystem # 存储类型为文件系统
  accessModes: # 访问模式
    - ReadWriteMany # 可被多节点读写
  persistentVolumeReclaimPolicy: Retain # 回收策略
  storageClassName: slow # 创建pv的存储类名，需要和 PVC 相同
  mountOptions: # 加载配置
    - hard
    - nfsvers=4.1
  nfs: # 连接到NFS
    path: /data/nfs/rw/test-pv # 存储路径
    server: 192.168.1.101 # nfs服务地址
