apiVersion: v1
kind: Pod
metadata:
  name: test-pve-pd
spec:
  containers:
  - image: nginx
    name: nginx-volume
    volumeMounts:
    - mountPath: /usr/share/nginx/html # 挂载到容器的哪个目录
      name: test-volume # 挂载哪个volume
  volumes:
  - name: test-volume
    persistentVolumeClaim: # 关联 PVC
      claimName: nfs-pvc # 要关联到哪个 pvc
