apiVersion: v1
kind: Service
metadata:
  name: tidb-dev-tidb
  namespace: kubernetes-dashboard
spec:
  selector:
    app.kubernetes.io/component: tidb
  ports:
    - protocol: TCP
      port: 4000
      # tidb 默认端口
      targetPort: 4000
