---
apiVersion: v1
kind: Secret
metadata:
  namespace: kubernetes-dashboard
  name: dsb-das-mysql-slave-secret
  labels:
    app: dashboard-additional-services-0.1.0
    release: dsb-das
data:
  username: cGtj
  password: NndiOGVIZ0xqZkhRM1hRMnM3U1Y=
  root-password: cVVrOFBBVzZXcDc4dmI5MnA5SlQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kubernetes-dashboard
  name: dsb-das-mysql-slave-config
  labels:
    app: dashboard-additional-services-0.1.0
    release: dsb-das
data:
  mysql.cnf: |-
    [mysqld]
    max_connect_errors=10
    max_connections=500
    max_user_connections=300

    log-output=FILE
    log-error=/var/log/mysqld/mysqld.log

    general_log=ON
    general_log_file=/var/log/mysqld/mysqld_log.log

    slow_query_log=ON
    slow_query_log_file=/var/log/mysqld/mysqld_slow_query.log
    long_query_time=10

    server_id=2
    log-bin=/var/log/mysqld/mysqld_bin
    read-only=1
    relay_log=/var/log/mysqld/mysqld-relay-bin
    log-slave-updates=on
    max_binlog_size=500M
    expire_logs_days=99

    interactive_timeout=1800
    wait_timeout=1800

    innodb_buffer_pool_size=8G
    sync_binlog=1
    query_cache_size=0

---
apiVersion: v1
kind: Service
metadata:
  namespace: kubernetes-dashboard
  name: dsb-das-mysql-slave
  labels:
    app: dashboard-additional-services-mysql-slave
    app_version: 0.1.0
    release: dsb-das
spec:
  ports:
    - port: 3306
  selector:
    app: dashboard-additional-services-mysql-slave
    app_version: 0.1.0
    release: dsb-das
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-dashboard
  name: dsb-das-mysql-slave
  labels:
    app: dashboard-additional-services-mysql-slave
    app_version: 0.1.0
    release: dsb-das
spec:
  selector:
    matchLabels:
      app: dashboard-additional-services-mysql-slave
      app_version: 0.1.0
      release: dsb-das
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dashboard-additional-services-mysql-slave
        app_version: 0.1.0
        release: dsb-das
    spec:
      containers:
        - image: 172.31.215.191:5000/iie-mysql:5.6.51
          name: dsb-das-mysql-container
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-slave-volume
            - mountPath: /var/log/mysqld
              name: mysql-slave-bin-volume
            - mountPath: /etc/mysql/conf.d
              name: mysql-slave-cnf-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsb-das-mysql-slave-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: dsb-das-mysql-slave-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsb-das-mysql-slave-secret
                  key: password
            - name: MYSQL_USER_HOST
              value: 10.%.%.%
            - name: MYSQL_DATABASE
              value: dashboard_data
          ports:
            - name: mysql-port
              containerPort: 3306

      nodeSelector:
        kubernetes.io/hostname: vm-0-4-centos

      volumes:
        - name: mysql-slave-volume
          hostPath:
            path: /workspace/.mysql-data
            type: Directory
        - name: mysql-slave-bin-volume
          hostPath:
            path: /workspace/.mysql-data
            type: Directory
        - name: mysql-slave-cnf-volume
          configMap:
            name: dsb-das-mysql-slave-config
