apiVersion: v1 # deployment api版本
kind: Service # 资源类型为service
metadata: # service 相关元数据，用于描述service的配置
  name: nginx-svc # service名称
  labels: # 定义service的标签
    app: nginx # 标签vaule的形式，名为app，值为nginx
spec: # 期望service按照以下描述开始创建
  selector: # 匹配哪些pod会被该service代理
    app: nginx-deploy # 所有匹配到这些标签的pod会被service代理
  ports: # 端口映射
  - port: 80 # service自己的端口，在使用内网ip访问时使用
    targetPort: 80 # 目标pod的端口
    name: web # 为这个端口起的名字
  type: NodePort # 随机启动一个端口（30000-32767），映射到ports端口中，该端是直接绑定在node上的，且集群中的每一个node都会绑定到这个端口
                 # 也可以用来将服务暴露给外部访问，但是不推荐。效率底，而且service是四层负载
